---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cqdjyhrb/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp Minuman.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp property-6.jpg $DEPLOYPATH
    - /bin/cp property-list.html $DEPLOYPATH
    - /bin/cp testimonial.html $DEPLOYPATH
    - /bin/cp sdf.html $DEPLOYPATH
    - /bin/cp -R CSS $DEPLOYPATH
    - /bin/cp -R image $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R lib $DEPLOYPATH